### ISSUE TITLE
Docker 支持

### ISSUE THREAD

**Issue by mr-cn** [wenguonideshou/zsky#5]
能否添加一个dockerfile方便在Docker上部署？
其实自己能写 不过不知道需要暴露哪些端口

**Comment by wenguonideshou** [comment]
抱歉，我没有操作过docker，所以无法提供dockerfile。
UDP端口全部开启，TCP端口只需要开启8000端口（在gunicorn.service里面指定的），如果nginx安装在本机，开启80端口。如果还有其他问题，请联系我的QQ

**Comment by mr-cn** [comment]
UDP端口全部开启？难道UDP监听的端口是随机的吗

**Comment by wenguonideshou** [comment]
UDP全部开启，DHT通讯的时候使用随机端口
